spring:
  datasource:
    url: 'jdbc:mariadb://localhost:3306/skill'
    username: 'skill'
    password: 'skill'
    driver-class-name: 'org.mariadb.jdbc.Driver'
  jpa:
    hibernate:
      ddl-auto: 'create-drop'